import React, { useState } from 'react';
import { Link } from "react-router-dom";

function CaptainSignup() {
  const [Firstname,SetFirstname]=useState('');
    const [Lastname,SetLastname]=useState('');
    const [email,Setemail]=useState('');
    const [password,setpassword]=useState('');
    const [CaptainData,setCaptainData]=useState({})
    const submitHadlers=(e)=>{
      e.preventDefault();
      setCaptainData({
        fullName:{
          Firstname:Firstname,
          Lastname:Lastname,
        },
        email:email,
        password:password
      })
      SetFirstname('')
      SetLastname('')
      Setemail('');
      setpassword('')
      
  
      console.log(CaptainData)
    }
  return (
     <div className='p-7 flex flex-col justify-between h-screen'>
          <img className='w-16   rounded mix-blend-multiply' src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYHo1ccLWKoeQ7KSWkeLAUmSC0xyDNJD3Dz5GqSZMqCQ&s=10" alt="" />
          <div>
            <form action=""  onSubmit={(e)=>{
              submitHadlers(e)
            }}>
    
            <h5 
              className='text-2xl 
                font-bold mb-6 
                text-black  mt-2
                text-left'>What's detail for Captain-register 
            </h5>
    
            <div className='flex gap-2'>
              <input type="text"
                required
    
                className='bg-[#eeee] rounded px-4 py-4 border w-1/2 placeholder:text-base text-black'
                placeholder='First name'
                name='First-name'
                value={Firstname}
                onChange={(e)=>{
                  SetFirstname(e.target.value);
                }}
              />
              <input type="text"
                className='bg-[#eeee] rounded px-4 py-4 border w-1/2 placeholder:text-base text-black'
                placeholder='Last name'
                value={Lastname}
                onChange={(e)=>{
                  SetLastname(e.target.value);
                }}
              />
            </div>
           
            <input type="Email"
              placeholder='Email' 
              required
              className='bg-[#eeee] rounded px-4 py-4 border w-full mt-4 placeholder:text-base text-black'
              value={email}
              onChange={(e)=>{
                Setemail(e.target.value);
              }}
            />
            <input type="Password"
              placeholder='Password' 
              required
              className='bg-[#eeee] rounded px-4 py-4 border w-full mt-4 placeholder:text-base text-black'
              value={password}
              onChange={(e)=>{
                setpassword(e.target.value);
              }}
            />

            <button 
               className='bg-[#111] p-10 mt-6 text-[#ffff] font-semibold rounded px-4 py-4  w-full placeholder:text-base '>
              Register_Captain
            </button> 
          </form>
    
            <p className='text-center mt-4'>Alredy have account? <Link to={'/captain-login'} className='text-blue-600'>Login_captain here</Link></p>
    
          </div>
    
          <div className='mt-24'>
                  <p className='text-[8px] leading-tight'>The site generated by reCaptha and the <span className='underline'>goolge privacy policies</span>
                  <span className='underline'>and Term of Service </span>
                  </p>
          </div>
    </div>
  )
}

export default CaptainSignup